/* src/config.h.  Generated by CMake from cmake/config.h.cmake */

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
#cmakedefine ENABLE_NLS @GOACCESS_CONFIG_ENABLE_NLS@

/* Define to 1 if you have the 'alarm' function. */
#cmakedefine HAVE_ALARM @HAVE_ALARM@

/* Define to 1 if you have the <arpa/inet.h> header file. */
#cmakedefine HAVE_ARPA_INET_H @HAVE_ARPA_INET_H@

/* HAVE_CIPHER_STD_NAME */
#cmakedefine HAVE_CIPHER_STD_NAME @HAVE_CIPHER_STD_NAME@

/* Define to 1 if you have the <curses.h> header file. */
#cmakedefine HAVE_CURSES_H @HAVE_CURSES_H@

/* Define if the GNU dcgettext() function is already present or preinstalled. */
#cmakedefine HAVE_DCGETTEXT @HAVE_DCGETTEXT@

/* Define to 1 if you have the <fcntl.h> header file. */
#cmakedefine HAVE_FCNTL_H @HAVE_FCNTL_H@

/* Define to 1 if you have the 'floor' function. */
#cmakedefine HAVE_FLOOR @HAVE_FLOOR@

/* Define to 1 if fseeko (and ftello) are declared in stdio.h. */
#cmakedefine HAVE_FSEEKO @HAVE_FSEEKO@

/* Build using GeoIP. */
#cmakedefine HAVE_GEOLOCATION @HAVE_GEOLOCATION@

/* Define to 1 if you have the 'gethostbyaddr' function. */
#cmakedefine HAVE_GETHOSTBYADDR @HAVE_GETHOSTBYADDR@

/* Define to 1 if you have the 'gethostbyname' function. */
#cmakedefine HAVE_GETHOSTBYNAME @HAVE_GETHOSTBYNAME@

/* Define if the GNU gettext() function is already present or preinstalled. */
#cmakedefine HAVE_GETTEXT @HAVE_GETTEXT@

/* Define to 1 if you have the 'gettimeofday' function. */
#cmakedefine HAVE_GETTIMEOFDAY @HAVE_GETTIMEOFDAY@

/* Define if you have the iconv() function and it works. */
#cmakedefine HAVE_ICONV @HAVE_ICONV@

/* Define to 1 if you have the <inttypes.h> header file. */
#cmakedefine HAVE_INTTYPES_H @HAVE_INTTYPES_H@

/* Define to 1 if you have the 'crypto' library (-lcrypto). */
#cmakedefine HAVE_LIBCRYPTO @HAVE_LIBCRYPTO@

/* Define to 1 if you have the 'curses' library (-lcurses). */
#cmakedefine HAVE_LIBCURSES @HAVE_LIBCURSES@

/* Define to 1 if you have the 'GeoIP' library (-lGeoIP). */
#cmakedefine HAVE_LIBGEOIP @HAVE_LIBGEOIP@

/* Define to 1 if you have the 'intl' library (-lintl). */
#cmakedefine HAVE_LIBINTL @HAVE_LIBINTL@

/* Define to 1 if you have the 'maxminddb' library (-lmaxminddb). */
#cmakedefine HAVE_LIBMAXMINDDB @HAVE_LIBMAXMINDDB@

/* Define to 1 if you have the 'ncurses' library (-lncurses). */
#cmakedefine HAVE_LIBNCURSES @HAVE_LIBNCURSES@

/* "ncursesw is present." */
#cmakedefine HAVE_LIBNCURSESW @HAVE_LIBNCURSESW@

/* Define to 1 if you have the 'nsl' library (-lnsl). */
#cmakedefine HAVE_LIBNSL @HAVE_LIBNSL@

/* Define to 1 if you have the 'pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the 'socket' library (-lsocket). */
#cmakedefine HAVE_LIBSOCKET @HAVE_LIBSOCKET@

/* Define to 1 if you have the 'ssl' library (-lssl). */
#cmakedefine HAVE_LIBSSL @HAVE_LIBSSL@

/* Define to 1 if you have the 'z' library (-lz). */
#cmakedefine HAVE_LIBZ @HAVE_LIBZ@

/* Define to 1 if you have the <limits.h> header file. */
#cmakedefine HAVE_LIMITS_H @HAVE_LIMITS_H@

/* Define to 1 if you have the <locale.h> header file. */
#cmakedefine HAVE_LOCALE_H @HAVE_LOCALE_H@

/* Define to 1 if you have the 'malloc' function. */
#cmakedefine HAVE_MALLOC @HAVE_MALLOC@

/* Define to 1 if you have the 'memmove' function. */
#cmakedefine HAVE_MEMMOVE @HAVE_MEMMOVE@

/* Define to 1 if you have the 'memset' function. */
#cmakedefine HAVE_MEMSET @HAVE_MEMSET@

/* Define to 1 if you have the 'mkfifo' function. */
#cmakedefine HAVE_MKFIFO @HAVE_MKFIFO@

/* Define to 1 if you have the <netdb.h> header file. */
#cmakedefine HAVE_NETDB_H @HAVE_NETDB_H@

/* Define to 1 if you have the <netinet/in.h> header file. */
#cmakedefine HAVE_NETINET_IN_H @HAVE_NETINET_IN_H@

/* Define to 1 if you have the <ncursesw/ncurses.h> header file. */
#cmakedefine HAVE_NCURSESW_NCURSES_H @HAVE_NCURSESW_NCURSES_H@

/* Define to 1 if you have the <ncurses.h> header file. */
#cmakedefine HAVE_NCURSES_H @HAVE_NCURSES_H@

/* Define to 1 if you have the <ncurses/ncurses.h> header file. */
#cmakedefine HAVE_NCURSES_NCURSES_H @HAVE_NCURSES_NCURSES_H@

/* Define to 1 if you have the 'poll' function. */
#cmakedefine HAVE_POLL @HAVE_POLL@

/* Define to 1 if the system has the type 'ptrdiff_t'. */
#define HAVE_PTRDIFF_T 1

/* Define to 1 if you have the 'realloc' function. */
#cmakedefine HAVE_REALLOC @HAVE_REALLOC@

/* Define to 1 if you have the 'realpath' function. */
#cmakedefine HAVE_REALPATH @HAVE_REALPATH@

/* Define to 1 if you have the 'regcomp' function. */
#cmakedefine HAVE_REGCOMP @HAVE_REGCOMP@

/* Define to 1 if you have the 'setlocale' function. */
#cmakedefine HAVE_SETLOCALE @HAVE_SETLOCALE@

/* Define to 1 if you have the 'SHA1Init' function. */
#cmakedefine HAVE_SHA1INIT @HAVE_SHA1INIT@

/* Define to 1 if you have the <sha1.h> header file. */
#cmakedefine HAVE_SHA1_H @HAVE_SHA1_H@

/* Define to 1 if you have the <sha.h> header file. */
#cmakedefine HAVE_SHA_H @HAVE_SHA_H@

/* Define to 1 if you have the 'socket' function. */
#cmakedefine HAVE_SOCKET @HAVE_SOCKET@

/* Define to 1 if 'stat' has the bug that it succeeds when given the
   zero-length file name argument. */
#cmakedefine HAVE_STAT_EMPTY_STRING_BUG @HAVE_STAT_EMPTY_STRING_BUG@

/* Define to 1 if you have the <stddef.h> header file. */
#cmakedefine HAVE_STDDEF_H @HAVE_STDDEF_H@

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H @HAVE_STDINT_H@

/* Define to 1 if you have the <stdio.h> header file. */
#cmakedefine HAVE_STDIO_H @HAVE_STDIO_H@

/* Define to 1 if you have the <stdlib.h> header file. */
#cmakedefine HAVE_STDLIB_H @HAVE_STDLIB_H@

/* Define to 1 if you have the 'strcasecmp' function. */
#cmakedefine HAVE_STRCASECMP @HAVE_STRCASECMP@

/* Define to 1 if you have the 'strchr' function. */
#cmakedefine HAVE_STRCHR @HAVE_STRCHR@

/* Define to 1 if you have the 'strcspn' function. */
#cmakedefine HAVE_STRCSPN @HAVE_STRCSPN@

/* Define to 1 if you have the 'strdup' function. */
#cmakedefine HAVE_STRDUP @HAVE_STRDUP@

/* Define to 1 if you have the 'strerror' function. */
#cmakedefine HAVE_STRERROR @HAVE_STRERROR@

/* Define to 1 if you have the 'strftime' function. */
#cmakedefine HAVE_STRFTIME @HAVE_STRFTIME@

/* Define to 1 if you have the <strings.h> header file. */
#cmakedefine HAVE_STRINGS_H @HAVE_STRINGS_H@

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H @HAVE_STRING_H@

/* Define to 1 if you have the 'strncasecmp' function. */
#cmakedefine HAVE_STRNCASECMP @HAVE_STRNCASECMP@

/* Define to 1 if you have the 'strpbrk' function. */
#define HAVE_STRPBRK 1

/* Define to 1 if you have the 'strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the 'strspn' function. */
#define HAVE_STRSPN 1

/* Define to 1 if you have the 'strstr' function. */
#cmakedefine HAVE_STRSTR @HAVE_STRSTR@

/* Define to 1 if you have the 'strtol' function. */
#cmakedefine HAVE_STRTOL @HAVE_STRTOL@

/* Define to 1 if you have the 'strtoull' function. */
#cmakedefine HAVE_STRTOULL @HAVE_STRTOULL@

/* Define to 1 if you have the <sys/socket.h> header file. */
#cmakedefine HAVE_SYS_SOCKET_H @HAVE_SYS_SOCKET_H@

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine HAVE_SYS_STAT_H @HAVE_SYS_STAT_H@

/* Define to 1 if you have the <sys/time.h> header file. */
#cmakedefine HAVE_SYS_TIME_H @HAVE_SYS_TIME_H@

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H @HAVE_SYS_TYPES_H@

/* Define to 1 if you have the 'timegm' function. */
#cmakedefine HAVE_TIMEGM @HAVE_TIMEGM@

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H @HAVE_UNISTD_H@

/* Build with zlib support */
#cmakedefine HAVE_ZLIB @HAVE_ZLIB@

/* Define to 1 if you have the <zlib.h> header file. */
#cmakedefine HAVE_ZLIB_H @HAVE_ZLIB_H@

/* Define to 1 if 'lstat' dereferences a symlink specified with a trailing
   slash. */
#cmakedefine LSTAT_FOLLOWS_SLASHED_SYMLINK @LSTAT_FOLLOWS_SLASHED_SYMLINK@

/* Name of package */
#define PACKAGE "@PACKAGE@"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"

/* Define to the full name of this package. */
#define PACKAGE_NAME "@PACKAGE_NAME@"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "@PACKAGE_STRING@"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "@PACKAGE_TARNAME@"

/* Define to the home page for this package. */
#define PACKAGE_URL "@PACKAGE_URL@"

/* Define to the version of this package. */
#define PACKAGE_VERSION "@PACKAGE_VERSION@"

/* Define to 1 if all of the C89 standard headers exist */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "@VERSION@"

/* Build using GNU getline. */
#cmakedefine WITH_GETLINE @GOACCESS_CONFIG_WITH_GETLINE@

/* Debug option */
#cmakedefine _DEBUG @GOACCESS_CONFIG_DEBUG@

/* Define to 1 if necessary to make fseeko visible. */
#cmakedefine _LARGEFILE_SOURCE

/* Define for Solaris 2.5.1 so the uint32_t typedef is not used. */
/* #undef _UINT32_T */
/* #undef _UINT64_T */
/* #undef _UINT8_T */
/* #undef const */
/* #undef int64_t */
/* #undef int8_t */
/* #undef off_t */
/* #undef size_t */
/* #undef uint32_t */
/* #undef uint64_t */
/* #undef uint8_t */
